services:
  sitespeed.io-testrunner:
    image: sitespeedio/testrunner:${SITESPEED_IO_TESTRUNNER_VERSION}
    env_file:
      - .env
    environment:
      redis_host: ${REDIS_HOST}
      location_name: ${LOCATION_NAME}
      docker_container: ${SITESPEED_IO_CONTAINER}
      docker_extraparameters: "--network=skynet"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    cap_add:
      - NET_ADMIN
    depends_on:
      redis:
        condition: service_healthy
      sitespeed.io-server:
        condition: service_healthy
    networks:
      - skynet