services:
  redis:
    image: redis:${REDIS_DOCKER_VERSION}
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always
    networks:
      - skynet
    volumes:
      - redis_data:/data
      - ./redis-conf:/usr/local/etc/redis/
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30
  postgresql:
    image: postgres:${POSTGRESQL_DOCKER_VERSION}
    restart: always
    networks:
      - skynet
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DB}
    volumes:
      - ./server/database/setup/:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 30
volumes:
  postgres-data:
  redis_data:
    driver: local
networks:
  skynet:
    name: skynet
